# Generated by Django 5.1.4 on 2026-07-27 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_categoryoffer_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
