# Generated by Django 5.1.4 on 2026-07-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['code']},
        ),
    ]
