# Generated by Django 5.1.4 on 2024-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='Unnamed Category', max_length=255),
            preserve_default=False,
        ),
    ]
