# Generated by Django 5.1.4 on 2024-12-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_created_at_categories_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='is_list',
            new_name='is_listed',
        ),
    ]
