# Generated by Django 5.1.4 on 2025-01-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categories_name'),
        ('offers', '0002_alter_categoryoffer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_category_offer', to='offers.categoryoffer'),
        ),
    ]
