# Generated by Django 5.1.4 on 2026-07-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categories_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-created_at']},
        ),
    ]
