# Generated by Django 5.1.4 on 2026-07-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_variant_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
