# Generated by Django 5.1.4 on 2024-12-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Phone_number',
        ),
    ]
