# Generated by Django 5.1.4 on 2026-07-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
