# Generated by Django 5.1.4 on 2025-01-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_final_amount_order_item_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed')], default='FAILED', max_length=15),
        ),
    ]
