# Generated by Django 5.1.4 on 2025-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_item_return_reason_order_item_return_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='return_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Not Requested', 'Not Requested')], default='Not Requested', max_length=20),
        ),
    ]
